@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

GET http://{{host}}/produtos

###

GET http://{{host}}/produtos

###

POST http://{{host}}/produtos
Content-Type: application/json

{
    "nome" : "A",
    "preco": 1,
    "descricao": "Descrição do Produto ",
    "quantidadeEmEstoque": 110
}

###

PUT http://{{host}}/produtos/5
Content-Type: application/json

{
    "nome": "Produto Ehh",
    "preco": 20.0,
    "descricao": "Descrição do Produto Ehh",
    "quantidadeEmEstoque": 300
}

###
DELETE http://{{host}}/produtos/4
