@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

GET http://{{host}}/produtos

###

GET http://{{host}}/produtos

###

POST http://{{host}}/produtos
Content-Type: application/json

{
    "nome" : "BBB",
    "preco": 1,
    "descricao": "Descrição do Produto BBB",
    "quantidadeEmEstoque": 110
}

###

PUT http://{{host}}/produtos/6
Content-Type: application/json

{
    "nome": "Produto Ehh",
    "preco": 1.0,
    "descricao": "Descrição do Produto Ehh",
    "quantidadeEmEstoque": 150
}

###
DELETE http://{{host}}/produtos/5
